feat(CTA-60) Client Create Profile
ebond07/CoupeTonArbre pull request #31
Opened 2023-12-29 06:33 UTC by drallo22

JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/CTA/boards/59/backlog?selectedIssue=CTA-60
## Context:
Created implementation of client profile so that a client is able to create their profile and have that information stored in the database, also implemented the functionality for the client to be able to view their information
## Changes
- Implemented functionality to create profile
- Implemented functionality to get a profile
- Created backend testing for service and controller methods
- Created frontend testing for profile page
- Created cypress functions for client and admin login
-  Other small changes
## Before and After UI (Required for UI-impacting PRs)

## Before
![Screenshot 2023-12-29 013214](https://github.com/ebond07/CoupeTonArbre/assets/43860617/4532afb8-184f-46e4-a286-192faed9d368)

## After
![Screenshot 2023-12-29 013012](https://github.com/ebond07/CoupeTonArbre/assets/43860617/7b9d8db9-96d6-4e0d-96ad-5b80b158bbf2)
![Screenshot 2023-12-29 013039](https://github.com/ebond07/CoupeTonArbre/assets/43860617/dc39f573-c445-4fce-80d8-63d3ff97d97a)

2023-12-29 21:25 UTC, ebond07 requested changes
Good addition, check out the comments I left, some are general questions about the functionality but some are concerns regarding the code.

2023-12-29 21:25 UTC, ebond07 commented on .gitignore
Be careful to not modify any of the lines in the git ignore as this could really mess up the repository. These added lines I imagine are harmless but I think you added them by mistake.

2023-12-29 21:25 UTC, ebond07 commented on coupetonarbrebackend/src/main/java/com/example/coupetonarbrebackend/User/BusinessLayer/ClientServiceImpl.java
> +        log.info("Client request {}", clientRequestDTO);
Could be a good idea to leave comments letting us know to remove these lines when we publish the website as once everything functions as wanted all additional logging isn't going to be needed.

2023-12-29 21:25 UTC, ebond07 commented on coupetonarbrebackend/src/main/java/com/example/coupetonarbrebackend/User/PresentationLayer/ClientRequestDTO.java
> +//    private String clientId;
If a clientId isn't being provided (which makes a lot more sense than having to provide one as it should be auto generated) then I think you can remove this line instead of commenting out as I don't believe we will ever need to uncomment it.

2023-12-29 21:25 UTC, ebond07 commented on coupetonarbrebackend/src/main/resources/data-mysql.sql
> +INSERT INTO clients (client_id, first_name, last_name, email,phone_number, address) VALUES ('google|123456789', 'Darrin', 'Cadd', 'dcadd5@ning.com', '(450) 938-5748','9 Cambridge Road, Havre-Saint-Pi
Could you explain this please, I'm assuming it has something to do with having a client with a google account but I could be completed wrong.

2023-12-29 21:25 UTC, ebond07 commented on coupetonarbrefrontend/src/pages/Profile.jsx
> +import swal from 'sweetalert';
Any reason you went with sweetalert over other options?

2023-12-29 21:25 UTC, ebond07 commented on coupetonarbrefrontend/src/pages/Profile.jsx
So we're using bootstrap now.

2023-12-29 21:25 UTC, ebond07 commented on coupetonarbrebackend/build.gradle
> +    testImplementation('com.h2database:h2')
I didn't think we would need to import h2 for testing purposes considering we aren't using it in production.

2023-12-29 22:16 UTC, drallo22 commented on .gitignore
I added something to the git ignore but then took it out as it  was np longer needed, these extra lines were accidental when I was deleting what I added.

2023-12-29 22:18 UTC, drallo22 commented on coupetonarbrebackend/build.gradle
> +    testImplementation('com.h2database:h2')
I attempted to use an h2 repository for testing but then stopped using it as I just used mocks instead of storing actual data in an h2 database, I forgot to remove those lines from the build.gradle

2023-12-29 22:22 UTC, drallo22 commented on coupetonarbrebackend/src/main/resources/data-mysql.sql
> +INSERT INTO clients (client_id, first_name, last_name, email,phone_number, address) VALUES ('google|123456789', 'Darrin', 'Cadd', 'dcadd5@ning.com', '(450) 938-5748','9 Cambridge Road, Havre-Saint-Pi
I wanted to test something, it has no purpose, I didn't change it back as it has no significance.

2023-12-29 22:23 UTC, drallo22 commented on coupetonarbrefrontend/src/pages/Profile.jsx
> +import swal from 'sweetalert';
It is being used by other classmates, I also find it looks nice as it gives a nice pop up in the middle of the screen unlike toastify.

2023-12-29 22:26 UTC, drallo22 commented on coupetonarbrefrontend/src/pages/Profile.jsx
Where do you see bootstrap?

2023-12-29 22:33 UTC, ebond07 commented on coupetonarbrefrontend/src/pages/Profile.jsx
> +            <div className="row w-75 m-auto">
this is bootstrap

2023-12-29 22:33 UTC, ebond07 commented on coupetonarbrefrontend/src/pages/Profile.jsx
bru, the div class names

2023-12-30 05:30 UTC, ebond07 approved these changes
Ottimo lavoro David, il codice è scritto bene e hai apportato le modifiche che avevo richiesto.

2023-12-30 19:47 UTC, Matthewtan9 approved these changes

2023-12-30 22:32 UTC, merged