conf(CTA-63) Setup Quote Request Backend Structure
ebond07/CoupeTonArbre pull request #33
Opened 2023-12-31 20:37 UTC by ebond07

JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/CTA/boards/59?selectedIssue=CTA-63
## Context:
Setting up the backend structure for quote requests so the team can begin work on this feature
## Changes
- Added all classes and interfaces necessary for the development of the feature
- Removed existing temp.txt files
- Created initial tests
- Implemented the Get All within the backend
- Did a tiny bit of cleanup, like a tiny bit

2023-12-31 21:11 UTC, drallo22 approved these changes
Take a look at the comment I left, if you agree with me just make the change and the rest looks good!

2023-12-31 21:11 UTC, drallo22 commented on coupetonarbrebackend/src/main/java/com/example/coupetonarbrebackend/QuoteRequest/PresentationLayer/QuoteRequestRequestDTO.java
> +    private String quoteRequestId;
Since quoteRequestId is being autogenerated is there a need to have it in the requestDTO

2023-12-31 21:18 UTC, ebond07 commented on coupetonarbrebackend/src/main/java/com/example/coupetonarbrebackend/QuoteRequest/BusinessLayer/QuoteRequestService.java
> +@Component
Yeah, otherwise it wasn't being recognized elsewhere in the project. Can't remember exactly where but I wasn't able to inject the service without this annotation.

2023-12-31 22:29 UTC, Matthewtan9 commented on coupetonarbrebackend/build.gradle
> +                minimum = 0.00
why the change from 0.90 to 0.00 and what does this do ?

2023-12-31 22:29 UTC, Matthewtan9 approved these changes

2024-01-01 00:37 UTC, ebond07 commented on coupetonarbrebackend/build.gradle
> +                minimum = 0.00
It's a temporary change for the requirement of Jacoco coverage for the build to pass. During setup stages like this we will rarely be able to reach 90% so I dropped it completely.

2024-01-01 19:01 UTC, drallo22 requested changes
Now that I have thought more about it I believe it wouldn't hurt to have the clientId part of the requestDTO as well

2024-01-01 19:14 UTC, ebond07 commented on coupetonarbrebackend/src/main/java/com/example/coupetonarbrebackend/QuoteRequest/PresentationLayer/QuoteRequestRequestDTO.java
> +    private String quoteRequestId;
There is not, thank you for bringing my attention to this.

2024-01-01 19:15 UTC, ebond07 commented
> Now that I have thought more about it I believe it wouldn't hurt to have the clientId part of the requestDTO as well

It definitely wouldn't hurt. I'll add it.

2024-01-01 19:19 UTC, drallo22 approved these changes

2024-01-01 19:20 UTC, merged